# Generated by cpp11: do not edit by hand

other_grow_ <- function(n) {
  .Call(`_ldlasb_other_grow_`, n)
}

rcpp_grow_ <- function(n) {
  .Call(`_ldlasb_rcpp_grow_`, n)
}

other_release_ <- function(n) {
  invisible(.Call(`_ldlasb_other_release_`, n))
}

rcpp_release_ <- function(n) {
  invisible(.Call(`_ldlasb_rcpp_release_`, n))
}
